INSERT INTO Equipos (id_equipo, nombre_equipo, pais, fabricante_moto, categoria) VALUES
(16, 'Leopard Racing', 'Italia', 'Honda', 'Moto3'),
(17, 'Liqui Moly Husqvarna Intact GP', 'Alemania', 'Husqvarna', 'Moto3'),
(18, 'CFMoto Aspar Team', 'España', 'CFMoto', 'Moto3'),
(19, 'Rivacold Snipers Team', 'Italia', 'Honda', 'Moto3'),
(20, 'Sic58 Squadra Corse', 'Italia', 'Honda', 'Moto3'),
(21, 'Boé Motorsports', 'España', 'KTM', 'Moto3'),
(22, 'CIP Green Power', 'Francia', 'KTM', 'Moto3'),
(23, 'MT Helmets – MSi', 'España', 'KTM', 'Moto3'),
(24, 'Red Bull GasGas Tech3', 'Francia', 'GasGas', 'Moto3'),
(25, 'MTA Team', 'Italia', 'KTM', 'Moto3');

INSERT INTO Equipos (id_equipo, nombre_equipo, pais, fabricante_moto, categoria) VALUES
-- Moto2 2012
(26, 'Marc VDS Racing Team', 'Bélgica', 'Kalex', 'Moto2'),
(27, 'Tech 3 Racing', 'Francia', 'Tech 3', 'Moto2'),
(28, 'Pons Racing', 'España', 'Kalex', 'Moto2'),
(29, 'Interwetten Paddock Moto2', 'Suiza', 'Suter', 'Moto2'),
(30, 'Speed Up', 'Italia', 'Suter', 'Moto2'),
(31, 'Italtrans Racing Team', 'Italia', 'Kalex', 'Moto2'),
(32, 'Gresini Racing Moto2', 'Italia', 'Suter', 'Moto2'),
(33, 'Mapfre Aspar Team Moto2', 'España', 'Suter', 'Moto2'),
(34, 'JiR Moto2', 'Japón', 'Moriwaki', 'Moto2'),
(35, 'NGM Forward Racing', 'Italia', 'Suter', 'Moto2'),
-- MotoGP 2012
(36, 'Repsol Honda Team', 'España', 'Honda', 'MotoGP'),
(37, 'Yamaha Factory Racing', 'Japón', 'Yamaha', 'MotoGP'),
(38, 'Ducati Team', 'Italia', 'Ducati', 'MotoGP'),
(39, 'LCR Honda MotoGP', 'Mónaco', 'Honda', 'MotoGP'),
(40, 'Cardion AB Motoracing', 'Chequia', 'Ducati', 'MotoGP'),
(41, 'Pramac Racing Team', 'Italia', 'Ducati', 'MotoGP'),
(42, 'San Carlo Honda Gresini', 'Italia', 'Honda', 'MotoGP'),
(43, 'Monster Yamaha Tech 3', 'Francia', 'Yamaha', 'MotoGP'),
(44, 'Power Electronics Aspar', 'España', 'ART', 'MotoGP'),
(45, 'Avintia Racing', 'España', 'BQR', 'MotoGP'),
(46, 'Speed Master', 'Italia', 'ART', 'MotoGP'),
(47, 'Paul Bird Motorsport', 'Reino Unido', 'ART', 'MotoGP'),
-- Moto3 2013-2024
(48, 'Ongetta-Rivacold', 'Italia', 'Honda', 'Moto3'),
(49, 'Ajo Motorsport', 'Finlandia', 'KTM', 'Moto3'),
(50, 'VisionTrack Racing', 'Reino Unido', 'Honda', 'Moto3'),
(51, 'Max Racing Team', 'Austria', 'Husqvarna', 'Moto3'),
(52, 'Prüstel GP', 'Alemania', 'KTM', 'Moto3'),
-- Moto2 2013-2024
(53, 'Idemitsu Honda Team Asia', 'Japón', 'Kalex', 'Moto2'),
(54, 'SAG Racing Team', 'España', 'Kalex', 'Moto2'),
(55, 'American Racing Team', 'EE.UU.', 'Kalex', 'Moto2'),
(56, 'Petronas Sprinta Racing', 'Malasia', 'Kalex', 'Moto2'),
(57, 'MV Agusta Forward Racing', 'Italia', 'MV Agusta', 'Moto2'),
(58, 'Fantic Racing', 'Italia', 'Kalex', 'Moto2'),
(59, 'QJMOTOR Gresini Moto2', 'Italia', 'Kalex', 'Moto2'),
-- MotoGP 2013-2024
(60, 'Aprilia Racing Team Gresini', 'Italia', 'Aprilia', 'MotoGP'),
(61, 'Suzuki Ecstar Team', 'Japón', 'Suzuki', 'MotoGP'),
(62, 'KTM Factory Racing', 'Austria', 'KTM', 'MotoGP'),
(63, 'RNF MotoGP Racing', 'Malasia', 'Aprilia', 'MotoGP'),
(64, 'Mooney VR46 Racing Team', 'Italia', 'Ducati', 'MotoGP'),
(65, 'Trackhouse Racing MotoGP', 'EE.UU.', 'Aprilia', 'MotoGP'),
(66, 'Prima Pramac Racing', 'Italia', 'Ducati', 'MotoGP'),
(67, 'Gresini Racing MotoGP', 'Italia', 'Ducati', 'MotoGP');